### ISSUE TITLE
xcheck.py new keys broken on windows

### ISSUE THREAD

**Issue by ace0** [ace0/xcheck#4]
Key lengths may be different on windows:

Newkeys appears to work and protect works, but process breaks:

Traceback (most recent call last):
  File "xcheck.py", line 95, in <module>
    fire.Fire(XCheckCli())
  File "C:\Users\User\Anaconda2\lib\site-packages\fire\core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "C:\Users\User\Anaconda2\lib\site-packages\fire\core.py", line 366, in _Fire
    component, remaining_args)
  File "C:\Users\User\Anaconda2\lib\site-packages\fire\core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "xcheck.py", line 68, in process
    privkeyFile=privkey)
  File "C:\Users\User\Desktop\xcheck-master\xcheck-master\xcheck\lib.py", line 83, in processJee
    err, reportingTxt = publicKeyDecrypt(privkeyFile, jeeText)
  File "C:\Users\User\Desktop\xcheck-master\xcheck-master\xcheck\lib.py", line 493, in publicKeyDecrypt
    msgKey = PKCS1_OAEP.new(privkey).decrypt(encKey)
  File "C:\Users\User\Anaconda2\lib\site-packages\Crypto\Cipher\PKCS1_OAEP.py", line 168, in decrypt
    raise ValueError("Ciphertext with incorrect length.")
ValueError: Ciphertext with incorrect length.

**Comment by ace0** [comment]
Couldn't reproduce this. Tested `python xcheck.py newkeys`; and various uses of xcheck and xreport. I think perhaps we were testing with a command line prompt but not the Anaconda prompt.
